#!/usr/bin/env python3
"""
pb_audit.py — Append-only audit log for all Privileged Brain commands.

Every command generated by the ^ trigger is logged here, including blocked ones.
The log is JSON Lines format, opened with O_APPEND for atomic writes.

Usage:
  python3 pb_audit.py log <nl> <cmd> <blocked> <cwd>   ← called by pb_trigger
  python3 pb_audit.py list [--last N] [--blocked]       ← view recent entries
  python3 pb_audit.py tail                               ← follow live
  python3 pb_audit.py stats                             ← summary stats
"""

import fcntl
import json
import os
import sys
import time
from pathlib import Path

AUDIT_LOG = Path.home() / ".pb_audit.jsonl"


def _write_entry(entry: dict) -> None:
    """Append one JSON entry atomically using O_APPEND."""
    line = json.dumps(entry, separators=(",", ":")) + "\n"
    # O_CREAT | O_APPEND | O_WRONLY — atomic appends on POSIX
    fd = os.open(AUDIT_LOG, os.O_CREAT | os.O_APPEND | os.O_WRONLY, 0o600)
    try:
        os.write(fd, line.encode())
    finally:
        os.close(fd)


def _read_entries(last: int = 0, blocked_only: bool = False) -> list[dict]:
    if not AUDIT_LOG.exists():
        return []
    entries = []
    with open(AUDIT_LOG) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                e = json.loads(line)
                if blocked_only and not e.get("blocked"):
                    continue
                entries.append(e)
            except json.JSONDecodeError:
                continue
    if last:
        entries = entries[-last:]
    return entries


def cmd_log(nl: str, cmd: str, blocked: str, cwd: str) -> None:
    entry = {
        "ts": time.time(),
        "ts_human": time.strftime("%Y-%m-%d %H:%M:%S"),
        "nl": nl.strip(),
        "cmd": cmd.strip(),
        "blocked": blocked.lower() == "true",
        "cwd": cwd.strip(),
    }
    _write_entry(entry)


def cmd_list(last: int = 20, blocked_only: bool = False) -> None:
    entries = _read_entries(last=last, blocked_only=blocked_only)
    if not entries:
        print("No audit log entries found.")
        return
    print(f"{'Time':>20}  {'B':>1}  {'Intent / Command'}")
    print("-" * 90)
    for e in entries:
        ts = e.get("ts_human", "?")
        blocked = "!" if e.get("blocked") else " "
        nl = e.get("nl", "")[:35]
        cmd = e.get("cmd", "")[:40]
        print(f"{ts:>20}  {blocked:>1}  {nl!r} → {cmd!r}")


def cmd_tail() -> None:
    print(f"Following {AUDIT_LOG} (Ctrl+C to stop)")
    import subprocess
    try:
        subprocess.run(["tail", "-f", str(AUDIT_LOG)])
    except KeyboardInterrupt:
        pass


def cmd_stats() -> None:
    entries = _read_entries()
    if not entries:
        print("No entries.")
        return
    total = len(entries)
    blocked = sum(1 for e in entries if e.get("blocked"))
    unique_nl = len({e.get("nl") for e in entries})
    size_kb = AUDIT_LOG.stat().st_size / 1024 if AUDIT_LOG.exists() else 0
    print(f"Total commands  : {total}")
    print(f"Blocked         : {blocked}  ({blocked/total*100:.1f}%)")
    print(f"Unique intents  : {unique_nl}")
    print(f"Log size        : {size_kb:.1f} KB  ({AUDIT_LOG})")
    if entries:
        first_ts = time.strftime("%Y-%m-%d", time.localtime(entries[0]["ts"]))
        last_ts = time.strftime("%Y-%m-%d", time.localtime(entries[-1]["ts"]))
        print(f"Date range      : {first_ts} → {last_ts}")


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    subcmd = sys.argv[1]

    if subcmd == "log":
        if len(sys.argv) < 6:
            sys.exit(1)
        cmd_log(sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])

    elif subcmd == "list":
        last = 20
        blocked_only = False
        args = sys.argv[2:]
        if "--last" in args:
            idx = args.index("--last")
            last = int(args[idx + 1]) if idx + 1 < len(args) else 20
        if "--blocked" in args:
            blocked_only = True
        cmd_list(last=last, blocked_only=blocked_only)

    elif subcmd == "tail":
        cmd_tail()

    elif subcmd == "stats":
        cmd_stats()

    else:
        print(f"Unknown subcommand: {subcmd}")
        sys.exit(1)


if __name__ == "__main__":
    main()
