# AUTO-GENERATED by scripts/export_mcpd_catalogue.py from
# controller/tool_catalogue.yaml. DO NOT EDIT MANUALLY.
# Regenerate with: python scripts/export_mcpd_catalogue.py emit --from-categories

SUPPORTED_ACTIONS = frozenset({
    "fs.delete",
    "fs.list",
    "fs.read",
    "fs.stat",
    "fs.write",
    "network.dns.read",
    "network.status",
    "package.install",
    "package.query",
    "package.remove",
    "package.upgrade",
    "process.inspect",
    "process.list",
    "service.logs",
    "service.restart",
    "service.start",
    "service.stop",
    "system.cpu",
    "system.disk",
    "system.memory",
    "system.status",
    "system.unsupported",
    "system.uptime",
})
