# AUTO-GENERATED by scripts/export_mcpd_catalogue.py
# DO NOT EDIT MANUALLY. Regenerate with:
#   python scripts/export_mcpd_catalogue.py emit --mcpd <path>
#
# This module is the canonical mapping of mcpd tools to tier behaviour.
# risk_classifier imports from here; CI G2 asserts parity via
#   python scripts/export_mcpd_catalogue.py check

MCPD_SCHEMA_VERSION = "1.0.0"

# All 22 tools mcpd advertises
ALL_TOOLS = frozenset({
    "fs.delete",
    "fs.list",
    "fs.read",
    "fs.stat",
    "fs.write",
    "network.dns.read",
    "network.status",
    "package.install",
    "package.query",
    "package.remove",
    "package.upgrade",
    "process.inspect",
    "process.list",
    "service.logs",
    "service.restart",
    "service.start",
    "service.stop",
    "system.cpu",
    "system.disk",
    "system.memory",
    "system.status",
    "system.uptime",
})

# Tier 0 — read-only; auto-execute; no prompt (14 tools)
TIER0_TOOLS = frozenset({
    "fs.list",
    "fs.read",
    "fs.stat",
    "network.dns.read",
    "network.status",
    "package.query",
    "process.inspect",
    "process.list",
    "service.logs",
    "system.cpu",
    "system.disk",
    "system.memory",
    "system.status",
    "system.uptime",
})

# Tier depends on runtime params (e.g. fs.write — $HOME vs outside) (1 tools)
CONDITIONAL_TIER_TOOLS = frozenset({
    "fs.write",
})

# Always Tier 3 — destructive; HITL required (1 tools)
DESTRUCTIVE_TOOLS = frozenset({
    "fs.delete",
})

# Tier 2 — system writes; auto-execute with audit (6 tools)
SYSTEM_WRITE_TOOLS = frozenset({
    "package.install",
    "package.remove",
    "package.upgrade",
    "service.restart",
    "service.start",
    "service.stop",
})
