# AUTO-GENERATED by scripts/export_mcpd_catalogue.py
# DO NOT EDIT MANUALLY. Regenerate with:
#   python scripts/export_mcpd_catalogue.py emit --mcpd <path>
#
# This module is the canonical mapping of mcpd tools to tier behaviour.
# risk_classifier imports from here; CI G2 asserts parity via
#   python scripts/export_mcpd_catalogue.py check

MCPD_SCHEMA_VERSION = "1.0.0"

# All 22 tools mcpd advertises
ALL_TOOLS = frozenset({
    "fs.delete",
    "fs.list",
    "fs.read",
    "fs.stat",
    "fs.write",
    "network.dns.read",
    "network.status",
    "package.install",
    "package.query",
    "package.remove",
    "package.upgrade",
    "process.inspect",
    "process.list",
    "service.logs",
    "service.restart",
    "service.start",
    "service.stop",
    "system.cpu",
    "system.disk",
    "system.memory",
    "system.status",
    "system.uptime",
})

# Tier 0 — read-only; auto-execute; no prompt (14 tools)
TIER0_TOOLS = frozenset({
    "fs.list",
    "fs.read",
    "fs.stat",
    "network.dns.read",
    "network.status",
    "package.query",
    "process.inspect",
    "process.list",
    "service.logs",
    "system.cpu",
    "system.disk",
    "system.memory",
    "system.status",
    "system.uptime",
})

# Tier depends on runtime params (e.g. fs.write — $HOME vs outside) (1 tools)
CONDITIONAL_TIER_TOOLS = frozenset({
    "fs.write",
})

# Always Tier 3 — destructive; HITL required (1 tools)
DESTRUCTIVE_TOOLS = frozenset({
    "fs.delete",
})

# Tier 2 — system writes; auto-execute with audit (6 tools)
SYSTEM_WRITE_TOOLS = frozenset({
    "package.install",
    "package.remove",
    "package.upgrade",
    "service.restart",
    "service.start",
    "service.stop",
})


# ── GUI tools (not in mcpd — manually maintained) ────────────────────────

GUI_READONLY_TOOLS = frozenset({
    "gui.ping",
    "gui.screenshot",
    "gui.find_element",
    "gui.get_window_list",
    "gui.get_element_tree",
})

GUI_WRITE_TOOLS = frozenset({
    "gui.click",
    "gui.type",
    "gui.select",
})

ALL_GUI_TOOLS = GUI_READONLY_TOOLS | GUI_WRITE_TOOLS


# ── RPA Bridge tools (not in mcpd — manually maintained) ────────────────

RPA_READONLY_TOOLS = frozenset({
    "rpa.ping",
    "rpa.find_by_image",
    "rpa.list_workflows",
})

RPA_WRITE_TOOLS = frozenset({
    "rpa.execute_workflow",
})

ALL_RPA_TOOLS = RPA_READONLY_TOOLS | RPA_WRITE_TOOLS
