"""iceui — Model Context Protocol server exposing gui.* + rpa.* + submit_intent to opencode.

v6.14 F-101 (2026-07-27): OC edition previously had no way to reach GUI
enumeration, screenshots, click/type automation, or Robot-Framework
workflows because mcpd (Rust) has no gui.*/rpa.* tools and opencode
bypasses the Python controller entirely. This module ships those
capabilities as a SECOND stdio MCP server that opencode connects to
alongside `icebreaker` (mcpd). Tools appear namespaced under `iceui_`
(e.g. `iceui_gui.get_window_list`, `iceui_rpa.execute_workflow`).

v6.17 M7.6a-1a (2026-08-10): adds the `submit_intent` tool — a single
entry point Gemini calls with a validated intent object. The handler
opens a UNIX socket to the Python Controller daemon and drives the
full 11-step pipeline (schema validation, risk classification, COW
preview, HITL, PB grammar-constrained tool call with M7.0.2 bounded
retry + QB-consult rescue, verifier, mcpd dispatch, summarise). This
is the surface that closes the OC INV-1 gap (audit rows A-1..A-8) and
makes every v6.16 M7.0.1 + M7.0.2 safety mechanism reach OC users. See
F-111 in `incremental/GROUND_TRUTH.md § 7`.

## Design

- **Hand-rolled MCP protocol**: no `mcp` Python package in the venv;
  JSON-RPC 2.0 over stdin/stdout is ~150 LOC, mirroring
  `src/mcpd/src/server.rs`. Methods implemented: `initialize`,
  `notifications/initialized` (no-op accept), `tools/list`, `tools/call`.
- **Schema reuse**: tool inputSchema comes verbatim from
  `gui_agent.protocol._PARAM_SCHEMAS` +
  `rpa_bridge.protocol._PARAM_SCHEMAS`. No duplication.
- **Subprocess isolation**: `tools/call` delegates via
  `agent_graph_nodes._dispatch_in_subprocess` — pyatspi's GLib mainloop
  requirement (F-88) is satisfied by spawning a fresh Python interpreter
  per call.
- **Error mapping**: mirrors mcpd's codes — -32700 parse, -32601
  method-not-found, -32602 invalid-params (schema fail), -32603 internal.
  Tool errors return `{"content":[...], "isError": true}` NOT a JSON-RPC
  error — that's the MCP tools/call convention.
"""

from __future__ import annotations

import json
import logging
import sys
import traceback
from typing import Any

# Reuse the existing schemas — no rewriting.
from gui_agent.protocol import (
    _PARAM_SCHEMAS as _GUI_SCHEMAS,
    ALL_GUI_METHODS,
)
from rpa_bridge.protocol import _PARAM_SCHEMAS as _RPA_SCHEMAS

_log = logging.getLogger("controller.mcp_gui_server")

SERVER_NAME = "iceui"
SERVER_VERSION = "1.0.0"
PROTOCOL_VERSION = "2025-06-18"  # matches mcpd's advertised version

# JSON-RPC error codes (JSON-RPC 2.0 spec + mcpd conventions).
_PARSE_ERROR = -32700
_INVALID_REQUEST = -32600
_METHOD_NOT_FOUND = -32601
_INVALID_PARAMS = -32602
_INTERNAL_ERROR = -32603

# GUI tool prefix (a bare `gui.` is unambiguous — the RpaBridge doesn't
# expose any `gui.*` methods and vice versa).
# v6.17 M7.6a-1a: `submit_intent` joins as a THIRD tool kind alongside
# gui/rpa. It's not in _GUI_SCHEMAS / _RPA_SCHEMAS because it doesn't
# dispatch to gui_worker/rpa_bridge — it forwards to the Controller
# daemon via UNIX socket. Enumerated separately + counted separately.
SUBMIT_INTENT_TOOL_NAME = "submit_intent"

_ALL_TOOL_NAMES = (
    tuple(sorted(_GUI_SCHEMAS.keys()))
    + tuple(sorted(_RPA_SCHEMAS.keys()))
    + (SUBMIT_INTENT_TOOL_NAME,)
)


def _tool_kind(name: str) -> str:
    if name == SUBMIT_INTENT_TOOL_NAME:
        return "submit_intent"
    if name.startswith("gui."):
        return "gui"
    if name.startswith("rpa."):
        return "rpa"
    return ""


# v6.17 M7.6a-1a: submit_intent input schema — validated at the MCP
# transport layer so opencode rejects malformed calls before they reach
# the Controller. The `intent` sub-object is a subset of intent.json
# (server-owned fields `intent_id`/`schema_version`/`timestamp` are
# generated by the Controller — Gemini MUST NOT emit them). The
# Controller re-validates against the full intent.json + risk-classifies
# + verifies before any tool executes — this MCP-layer schema is defense
# in depth, not the authoritative validator.
_SUBMIT_INTENT_SCHEMA: dict = {
    "type": "object",
    "required": ["session_id", "intent"],
    "additionalProperties": False,
    "properties": {
        "session_id": {
            "type": "string",
            "minLength": 1,
            "maxLength": 128,
            "description": "Opaque session identifier. Use the same value across a conversation to preserve session state (cwd, recent_commands). Not authenticated — the daemon trusts opencode's assertion.",
        },
        "intent": {
            "type": "object",
            "required": ["action", "reason", "risk_level"],
            "additionalProperties": True,  # server re-validates
            "properties": {
                "action": {
                    "type": "string",
                    "maxLength": 64,
                    "description": "MCP tool name (e.g. 'fs.list', 'package.install', 'system.status'). Must match a tool in mcpd's catalogue — the Controller re-validates and rejects unknown actions.",
                },
                "target": {
                    "type": "string",
                    "maxLength": 512,
                    "description": "Primary target — absolute path, service name, PID, package name. Shell metacharacters rejected by the Controller.",
                },
                "params": {
                    "type": "object",
                    "description": "Tool-specific parameters. Validated against the tool's JSON Schema.",
                },
                "content": {
                    "type": "string",
                    "maxLength": 65536,
                    "description": "Optional verbatim payload for the intent (e.g. bytes to write for fs.write). Copied into params.content verbatim by PB.",
                },
                "pb_hint": {
                    "type": "string",
                    "maxLength": 2048,
                    "description": "Optional short coaching text for the PB executor — describe which tool-schema field carries the semantic payload and any format constraints. ≤ 200 chars recommended.",
                },
                "reason": {
                    "type": "string",
                    "enum": ["user_requested", "ai_autonomous", "scheduled"],
                    "description": "Why this intent was generated. Use 'user_requested' when translating a user message.",
                },
                "risk_level": {
                    "type": "string",
                    "enum": ["read_only", "low", "medium", "high", "critical"],
                    "description": "Initial risk tier guess. The Controller re-classifies via risk_classifier.py — Gemini's value is advisory only.",
                },
            },
        },
    },
}


def _build_tools_list() -> list[dict]:
    """Materialize the tools/list response payload from the schemas.

    Each entry: {name, description, inputSchema}. Descriptions come from
    a small hand-authored table below since gui_agent/rpa_bridge don't
    export prose descriptions — opencode displays these in its tool
    catalog UI so they should be useful.
    """
    tools: list[dict] = []
    for name in sorted(_GUI_SCHEMAS.keys()):
        tools.append({
            "name": name,
            "description": _TOOL_DESCRIPTIONS.get(name, "GUI helper"),
            "inputSchema": _GUI_SCHEMAS[name],
        })
    for name in sorted(_RPA_SCHEMAS.keys()):
        tools.append({
            "name": name,
            "description": _TOOL_DESCRIPTIONS.get(name, "RPA helper"),
            "inputSchema": _RPA_SCHEMAS[name],
        })
    # v6.17 M7.6a-1a: submit_intent is the ONLY tool Gemini gets when
    # OC_MODE=submit_intent_only (via gen-oc-config.sh permission map).
    # In legacy_direct mode it appears alongside gui/rpa tools but
    # opencode's permission gate still governs which ones fire.
    tools.append({
        "name": SUBMIT_INTENT_TOOL_NAME,
        "description": _TOOL_DESCRIPTIONS.get(
            SUBMIT_INTENT_TOOL_NAME, "Submit a validated intent to the Controller."
        ),
        "inputSchema": _SUBMIT_INTENT_SCHEMA,
    })
    return tools


_TOOL_DESCRIPTIONS: dict[str, str] = {
    "gui.ping": "Returns AT-SPI + screenshot subsystem availability.",
    "gui.screenshot": "Capture a PNG screenshot of a window; returns path + hash + dimensions.",
    "gui.find_element": "Find a single AT-SPI element by role + accessible name inside a window.",
    "gui.get_window_list": "Enumerate open windows: title, app name, PID, geometry.",
    "gui.get_element_tree": "Return the AT-SPI accessibility tree for a window (bounded depth).",
    "gui.click": "Click an AT-SPI element identified by (window, role, name).",
    "gui.type": "Type text into a focused AT-SPI element (max 4096 chars).",
    "gui.select": "Set the value of a selectable AT-SPI element (dropdown, checkbox, radio).",
    # ── Fix V (v6.15) vision-grounded UI automation ──
    "gui.parse_screen": (
        "Screenshot a window and call the vision model to return a "
        "structured list of every clickable element (buttons, inputs, "
        "links, icons) with pixel boxes + captions + kind + confidence. "
        "Writes an annotated preview PNG and fires a desktop notification "
        "so the user sees it before any grounded action."
    ),
    "gui.click_at_coords": (
        "Raw pixel click at (x, y). Button ∈ {left, right, middle}, "
        "count ∈ {1, 2, 3}. HiDPI-aware — coordinates are physical pixels "
        "as returned by the vision model."
    ),
    "gui.type_at_coords": (
        "Focus-click at (x, y) then type text (≤4096 chars) into the "
        "focused element. Combines a click and a type into one atomic call."
    ),
    "gui.drag": (
        "Mouse drag from (x1, y1) to (x2, y2) with optional intermediate "
        "waypoints for gesture-style drags. Configurable button and hold "
        "duration."
    ),
    "gui.scroll": (
        "Scroll ‘amount’ wheel clicks at (x, y). Direction ∈ "
        "{up, down, left, right}."
    ),
    "gui.hover": (
        "Move the mouse cursor to (x, y) without clicking. Useful for "
        "revealing tooltips or hover-state UI before deciding to click."
    ),
    "gui.press_key": (
        "Press one key or key combo, e.g. 'ctrl+s', 'escape', 'F12'. "
        "Combos are '+'-separated; each token is checked against an "
        "allowlist so shell-injection patterns are rejected structurally."
    ),
    "gui.key_sequence": (
        "Execute a mixed sequence of key combos and typed text atomically. "
        "Accepts a list of strings (heuristically classified) or explicit "
        "{type: 'key'|'text', ...} dicts. Stops at the first failure."
    ),
    "gui.grounded_click": (
        "Natural-language click: given a window and a description like "
        "'the Send button', screenshot + parse the window with the vision "
        "model, ask the language model to pick which element matches, "
        "then click its centroid. Emits an annotated preview PNG with the "
        "target highlighted before firing."
    ),
    "gui.grounded_type": (
        "Natural-language type: like grounded_click but after picking the "
        "element, click-to-focus and then type the given text into it. "
        "Best for form fields ('the URL bar', 'the search input')."
    ),
    "gui.grounded_drag": (
        "Natural-language drag: given a window plus source_prompt and "
        "target_prompt, parse once, pick BOTH endpoints in a single LLM "
        "call, then drag the source element's centroid to the target's."
    ),
    "gui.grounded_scroll": (
        "Natural-language scroll: pick a scroll region by description, "
        "then scroll it in the given direction by the given amount "
        "(default 3)."
    ),
    "rpa.ping": "Returns Robot Framework + /dev/uinput availability.",
    "rpa.execute_workflow": (
        "Run a Robot Framework workflow of allowlisted keywords; "
        "returns per-step timing + screenshots + effect verification."
    ),
    "rpa.find_by_image": "Locate a UI element by template image match; returns bbox + confidence.",
    "rpa.list_workflows": "List Robot Framework workflow files present in the scratch dir.",
    "submit_intent": (
        "Submit a validated intent to the Icebreaker Controller for safe "
        "execution. Translate the user's natural-language request into an "
        "intent object with fields: action (MCP tool name like 'fs.list' or "
        "'package.install'), target (path/service/package), params (tool-"
        "specific args), optional content (verbatim payload bytes), optional "
        "pb_hint (short coaching text ≤200 chars), reason ('user_requested'), "
        "risk_level ('read_only'|'low'|'medium'|'high'|'critical'). Include "
        "session_id to preserve session state. The Controller re-validates, "
        "risk-classifies, previews any destructive op with a real dry-run "
        "diff, runs HITL if needed, generates the constrained tool call via "
        "the Privileged Brain, verifies, dispatches through the sandboxed "
        "mcpd daemon, and returns a natural-language summary of the result. "
        "This is the ONLY tool you need for filesystem, package, network, "
        "process, and service operations — do not call fs.*/package.*/etc. "
        "directly."
    ),
}


def _make_error_response(msg_id: Any, code: int, message: str) -> dict:
    return {"jsonrpc": "2.0", "id": msg_id, "error": {"code": code, "message": message}}


def _make_result_response(msg_id: Any, result: Any) -> dict:
    return {"jsonrpc": "2.0", "id": msg_id, "result": result}


def _handle_initialize(msg_id: Any, _params: dict) -> dict:
    return _make_result_response(msg_id, {
        "protocolVersion": PROTOCOL_VERSION,
        "capabilities": {"tools": {"listChanged": False}},
        "serverInfo": {"name": SERVER_NAME, "version": SERVER_VERSION},
    })


def _handle_tools_list(msg_id: Any, _params: dict) -> dict:
    return _make_result_response(msg_id, {"tools": _build_tools_list()})


# V.6f (2026-08-02) — module-level config cache. Loaded lazily on
# first _handle_tools_call. See _get_gui_cfg / _get_rpa_cfg below.
# CT-scan P0-3 remediation: pre-V.6f this file hardcoded cfg=None
# when calling _dispatch_in_subprocess, so the entire
# [gui.vision]/[gui.trust]/[gui.preview]/[gui.geometry] TOML surface
# was silently ignored on the OC edition dispatch path.
_CONFIG_CACHE: dict = {"loaded": False, "gui": None, "rpa": None}


def _get_cfg_for_kind(kind: str) -> Any:
    """Return the Gui/RpaConfig instance for this dispatch kind, loaded
    from `~/.config/icebreaker/controller.toml` (or $XDG_CONFIG_HOME).
    Falls back to dataclass defaults if the config file doesn't exist
    or fails to parse — the MCP server MUST boot even if config is
    broken, otherwise every tool call hard-fails."""
    if not _CONFIG_CACHE["loaded"]:
        try:
            from .config import load, GuiConfig, RpaConfig
            cfg = load()
            _CONFIG_CACHE["gui"] = cfg.gui
            _CONFIG_CACHE["rpa"] = cfg.rpa
        except Exception as exc:  # noqa: BLE001
            # Missing config file, bad TOML, schema violation — log
            # once and fall back to dataclass defaults so we don't
            # take the MCP server down.
            try:
                from .config import GuiConfig, RpaConfig
                _CONFIG_CACHE["gui"] = GuiConfig()
                _CONFIG_CACHE["rpa"] = RpaConfig()
            except Exception:  # noqa: BLE001
                # Even the imports failed — pass empty dict and let
                # gui_worker use its own hardcoded defaults.
                _CONFIG_CACHE["gui"] = None
                _CONFIG_CACHE["rpa"] = None
            import sys as _sys
            print(
                f"mcp_gui_server: config load failed "
                f"({type(exc).__name__}: {exc}); using dataclass defaults",
                file=_sys.stderr, flush=True,
            )
        _CONFIG_CACHE["loaded"] = True
    return _CONFIG_CACHE["gui"] if kind == "gui" else _CONFIG_CACHE["rpa"]


# ── v6.17 M7.6a-1a: submit_intent daemon-socket client ──────────────
#
# Minimal one-shot JSON-RPC client — deliberately NOT reusing the full
# DaemonClient in `controller/client.py` because that class is designed
# for a long-lived REPL with a reader thread + HITL presenter + reconnect
# logic. For the submit_intent flow we want a single connect → send →
# collect notifications → read response → close. Simpler + more testable.
#
# HITL v0 behaviour: notifications of `hitl.prompt` are surfaced back to
# opencode as part of the tool result narration; the user must then invoke
# a follow-up MCP tool (or a separate mechanism) to respond. Interactive
# HITL response wiring is a follow-up sub-commit — not scoped to M7.6a-1a.

# Default socket path for the shipped ISO. Can be overridden via
# ICEBREAKER_CONTROLLER_SOCK env var (e.g. tests, dev on Mac).
_DEFAULT_DAEMON_SOCK = "/run/icebreaker/controller.sock"

# Timeout budget for the WHOLE submit_intent round-trip. Chosen to
# accommodate: opencode → daemon (ms) + Steps 2-4 (~50ms) + optional
# HITL wait (bounded by daemon's own timeout, typically 30s) + Step 6
# PB call under Rosetta 2 emulation (up to 3 min per attempt, 3 attempts
# with M7.0.2 retry loop) + mcpd dispatch (up to 120s per M7.0.1) +
# summariser call. Real-user native latency: ~2-5s per turn.
_SUBMIT_INTENT_TIMEOUT_S = 900.0


def _handle_submit_intent(msg_id: Any, params: dict) -> dict:
    """v6.17 M7.6a-1a: forward a pre-formed intent to the Controller daemon.

    Opens a UNIX socket, sends JSON-RPC `intent.run`, collects streaming
    notifications, waits for the final response, and returns an MCP tool
    result whose `content` field carries the natural-language summary (or
    error narration on failure). Handles socket connect errors, timeouts,
    and daemon-side error responses without ever raising.
    """
    import os
    import socket as _socket
    import time as _time

    session_id = params.get("session_id") or ""
    intent = params.get("intent") or {}
    if not isinstance(session_id, str) or not session_id:
        return _make_result_response(msg_id, {
            "content": [{"type": "text", "text": "submit_intent: session_id is required"}],
            "isError": True,
        })
    if not isinstance(intent, dict) or not intent:
        return _make_result_response(msg_id, {
            "content": [{"type": "text", "text": "submit_intent: intent must be a non-empty object"}],
            "isError": True,
        })

    sock_path = os.environ.get(
        "ICEBREAKER_CONTROLLER_SOCK", _DEFAULT_DAEMON_SOCK,
    )
    sock_path = os.path.expanduser(sock_path)

    from .protocol import JsonRpcRequest, is_notification, is_response
    req = JsonRpcRequest(
        method="intent.run",
        params={"intent": intent, "session_id": session_id},
    )
    request_id = req.id

    try:
        sock = _socket.socket(_socket.AF_UNIX, _socket.SOCK_STREAM)
        sock.settimeout(_SUBMIT_INTENT_TIMEOUT_S)
        sock.connect(sock_path)
    except (OSError, _socket.error) as exc:
        return _make_result_response(msg_id, {
            "content": [{"type": "text", "text": (
                f"submit_intent: cannot reach Icebreaker Controller daemon at "
                f"{sock_path} ({type(exc).__name__}: {exc}). Is icebreaker-controller.service running?"
            )}],
            "isError": True,
        })

    notifications: list[dict] = []
    final_response: dict | None = None
    error_summary: str | None = None
    deadline = _time.monotonic() + _SUBMIT_INTENT_TIMEOUT_S

    try:
        sock.sendall(req.to_bytes())

        # Read line-delimited JSON until we see the response matching
        # our request_id (or timeout / socket close).
        buf = b""
        while final_response is None:
            remaining = deadline - _time.monotonic()
            if remaining <= 0:
                error_summary = (
                    f"submit_intent: timed out after {_SUBMIT_INTENT_TIMEOUT_S:.0f}s "
                    f"waiting for daemon response ({len(notifications)} events seen)"
                )
                break
            sock.settimeout(min(remaining, 5.0))
            try:
                chunk = sock.recv(65536)
            except _socket.timeout:
                # Non-fatal — poll deadline + continue.
                continue
            if not chunk:
                error_summary = (
                    f"submit_intent: daemon closed connection before responding "
                    f"({len(notifications)} events seen)"
                )
                break
            buf += chunk
            while b"\n" in buf:
                line, buf = buf.split(b"\n", 1)
                if not line.strip():
                    continue
                try:
                    msg = json.loads(line.decode("utf-8"))
                except (json.JSONDecodeError, UnicodeDecodeError) as exc:
                    _log.warning("submit_intent: malformed daemon line: %s", exc)
                    continue
                if is_notification(msg):
                    notifications.append(msg)
                    continue
                if is_response(msg) and msg.get("id") == request_id:
                    final_response = msg
                    break
                # Unrelated response id (out-of-band from other client
                # sharing the same socket path? unlikely but tolerated).
                _log.warning("submit_intent: ignoring unrelated msg id=%r", msg.get("id"))
    finally:
        try:
            sock.close()
        except Exception:  # noqa: BLE001
            pass

    if error_summary is not None:
        return _make_result_response(msg_id, {
            "content": [{"type": "text", "text": error_summary}],
            "isError": True,
        })

    assert final_response is not None  # loop invariant if no error_summary

    # Daemon returned a JSON-RPC error envelope
    if "error" in final_response:
        err = final_response["error"]
        return _make_result_response(msg_id, {
            "content": [{"type": "text", "text": (
                f"submit_intent: Controller rejected intent — "
                f"{err.get('code', '?')} {err.get('message', 'unknown error')}"
            )}],
            "isError": True,
        })

    # Success: daemon returned a result dict shaped like TurnResult.
    result = final_response.get("result") or {}
    success = bool(result.get("success"))
    output = result.get("output") or ""
    outcome = result.get("outcome") or "unknown"
    tier = result.get("tier")

    # Build the tool result content: primary text is the summariser
    # narration; a machine-readable second content block carries the
    # full envelope for opencode's audit / retry logic.
    text_narration = output or f"(no summary — outcome={outcome})"
    envelope_json = json.dumps({
        "outcome": outcome,
        "tier": tier,
        "success": success,
        "notifications_count": len(notifications),
        "duration_ms": result.get("duration_ms"),
        "cost_usd": result.get("cost_usd"),
    }, separators=(",", ":"))

    return _make_result_response(msg_id, {
        "content": [
            {"type": "text", "text": text_narration},
            {"type": "text", "text": f"__envelope__: {envelope_json}"},
        ],
        "isError": not success,
    })


def _handle_tools_call(msg_id: Any, params: dict) -> dict:
    tool_name = params.get("name") or ""
    arguments = params.get("arguments") or {}

    kind = _tool_kind(tool_name)

    # v6.17 M7.6a-1a: submit_intent has its own handler that forwards
    # to the Controller daemon via UNIX socket. Not subprocess-dispatched
    # like gui/rpa.
    if kind == "submit_intent":
        return _handle_submit_intent(msg_id, arguments)

    if kind not in ("gui", "rpa"):
        return _make_result_response(msg_id, {
            "content": [{"type": "text", "text": f"unknown tool: {tool_name!r}"}],
            "isError": True,
        })

    # Delegate to the existing subprocess dispatcher — same code path
    # the current-edition controller uses. Handles timeout, spawn
    # failure, non-zero exit, parse error. Never raises.
    # V.6f: pass the loaded [gui]/[rpa] TOML section so downstream
    # [gui.vision] etc are honored on the OC edition too (CT-scan P0-3).
    from .agent_graph_nodes import _dispatch_in_subprocess
    envelope = _dispatch_in_subprocess(
        kind=kind,
        tool_call={"tool": tool_name, "params": arguments},
        cfg=_get_cfg_for_kind(kind),
        timeout_s=15.0,  # slightly longer than dispatcher's 10s to survive
                        # slow AT-SPI enumeration on cold Firefox windows
    )

    if envelope.get("ok"):
        payload_json = json.dumps(envelope.get("result", {}), separators=(",", ":"))
        return _make_result_response(msg_id, {
            "content": [{"type": "text", "text": payload_json}],
            "isError": False,
        })
    return _make_result_response(msg_id, {
        "content": [{"type": "text", "text": envelope.get("error", "unknown dispatch failure")}],
        "isError": True,
    })


_METHOD_HANDLERS = {
    "initialize": _handle_initialize,
    "tools/list": _handle_tools_list,
    "tools/call": _handle_tools_call,
}


def _handle_line(line: str) -> dict | None:
    """Parse + route one JSON-RPC line. Returns response dict or None
    (for notifications that don't require a response)."""
    try:
        msg = json.loads(line)
    except json.JSONDecodeError:
        return _make_error_response(None, _PARSE_ERROR, "invalid JSON")
    if not isinstance(msg, dict):
        return _make_error_response(None, _INVALID_REQUEST, "message must be an object")
    if msg.get("jsonrpc") != "2.0":
        return _make_error_response(msg.get("id"), _INVALID_REQUEST, "jsonrpc must be '2.0'")

    method = msg.get("method")
    msg_id = msg.get("id")
    params = msg.get("params") or {}

    # Notifications have no `id` — spec says the server MUST NOT respond.
    # `notifications/initialized` is the canonical one from the MCP
    # handshake; accept-and-ignore per the protocol.
    is_notification = "id" not in msg
    if is_notification:
        if method == "notifications/initialized":
            return None
        # Unknown notification: silently drop (per JSON-RPC 2.0 spec).
        return None

    handler = _METHOD_HANDLERS.get(method)
    if handler is None:
        return _make_error_response(msg_id, _METHOD_NOT_FOUND, f"method not found: {method!r}")

    try:
        return handler(msg_id, params)
    except Exception as exc:  # noqa: BLE001 — server MUST NOT crash on handler failure
        _log.exception("mcp_gui_server: handler %s raised", method)
        return _make_error_response(
            msg_id, _INTERNAL_ERROR,
            f"internal error: {type(exc).__name__}: {exc}",
        )


def _write_response(resp: dict) -> None:
    line = json.dumps(resp, separators=(",", ":")) + "\n"
    sys.stdout.write(line)
    sys.stdout.flush()


_EXPECTED_TOOL_COUNT = 25
# v6.14 F-101 (Fix M) shipped 12 tools (8 gui.* AT-SPI + 4 rpa.*).
# v6.15 Fix V.4 added 12 vision-grounded tools (parse_screen +
# click/type/drag/scroll/hover + press_key/key_sequence +
# grounded_click/type/drag/scroll) — total 24.
# v6.17 M7.6a-1a added `submit_intent` — the Controller-daemon
# forwarder that makes OC edition inherit v6.16 M7.0.1 + M7.0.2 safety
# features. Total 25.
# Smoke-gate L3 asserts this count; drift in either direction means a
# schema was added/removed without the count being updated.


def _self_test() -> int:
    """--self-test: verify the handshake round-trips + tools/list returns
    the expected 25 tools (24 gui/rpa + submit_intent). Used by
    smoke-gate L3 assertion."""
    init_req = json.dumps({
        "jsonrpc": "2.0", "id": 1, "method": "initialize",
        "params": {
            "protocolVersion": PROTOCOL_VERSION,
            "capabilities": {},
            "clientInfo": {"name": "smoke-gate", "version": "0.0"},
        },
    })
    init_resp = _handle_line(init_req)
    if not init_resp or "result" not in init_resp:
        print(f"self-test FAILED: initialize returned {init_resp!r}", file=sys.stderr)
        return 1

    tl_req = json.dumps({"jsonrpc": "2.0", "id": 2, "method": "tools/list"})
    tl_resp = _handle_line(tl_req)
    if not tl_resp or "result" not in tl_resp:
        print(f"self-test FAILED: tools/list returned {tl_resp!r}", file=sys.stderr)
        return 1
    tools = tl_resp["result"].get("tools") or []
    if len(tools) != _EXPECTED_TOOL_COUNT:
        print(
            f"self-test FAILED: expected {_EXPECTED_TOOL_COUNT} tools, "
            f"got {len(tools)}: "
            f"{[t['name'] for t in tools]}",
            file=sys.stderr,
        )
        return 1
    print(f"self-test OK: initialize + tools/list ({len(tools)} tools)", file=sys.stderr)
    return 0


def main() -> int:
    if "--self-test" in sys.argv:
        return _self_test()

    # Blocking stdin read loop, one JSON message per line. opencode
    # keeps the connection open across many tool calls, so `for line in
    # sys.stdin` is the natural shape (blocks on EOF from opencode).
    try:
        for raw_line in sys.stdin:
            line = raw_line.strip()
            if not line:
                continue
            resp = _handle_line(line)
            if resp is not None:
                _write_response(resp)
    except (KeyboardInterrupt, BrokenPipeError):
        return 0
    except Exception as exc:  # noqa: BLE001 — never propagate; log + exit clean
        _log.exception("mcp_gui_server: unhandled exception in main loop: %s", exc)
        traceback.print_exc(file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
