#!/usr/bin/env python3
"""
risk_classifier.py — Tier 0–3 risk classification for Intent Objects.

Tiers:
  Tier 0 — Read-only operations. Auto-execute. No prompt. No notification.
  Tier 1 — Low-risk writes (user home dir, user services). Auto-execute + audit log.
  Tier 2 — Medium-risk (system services, package install). Auto-execute + notification.
  Tier 3 — High/critical (outside home dir, /etc/sudoers, /boot, /root, ...). BLOCK + HITL prompt.

The tool-set frozensets (TIER0_TOOLS, CONDITIONAL_TIER_TOOLS, DESTRUCTIVE_TOOLS,
SYSTEM_WRITE_TOOLS, ALL_TOOLS) are imported from ._mcpd_tools, which is
auto-generated by scripts/export_mcpd_catalogue.py against mcpd's actual
22-tool catalogue. Drift between this module and mcpd is enforced as a CI
gate (G2): `python scripts/export_mcpd_catalogue.py check`.

Usage:
  from risk_classifier import classify, Tier
  result = classify(intent)   # returns Tier + explanation
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass
from enum import IntEnum
from typing import Optional

from ._mcpd_tools import (
    ALL_TOOLS,
    CONDITIONAL_TIER_TOOLS,
    DESTRUCTIVE_TOOLS,
    GUI_READONLY_TOOLS,
    GUI_WRITE_TOOLS,
    SYSTEM_WRITE_TOOLS,
    TIER0_TOOLS,
)


class Tier(IntEnum):
    READ_ONLY = 0   # auto-execute, no UI
    LOW       = 1   # auto-execute + audit log
    MEDIUM    = 2   # auto-execute + notification
    HIGH      = 3   # BLOCK — requires explicit user approval


@dataclass
class ClassificationResult:
    tier: Tier
    reason: str
    reversible: bool
    blocked_pattern: Optional[str] = None

    @property
    def requires_hitl(self) -> bool:
        return self.tier == Tier.HIGH

    @property
    def auto_execute(self) -> bool:
        return self.tier in (Tier.READ_ONLY, Tier.LOW, Tier.MEDIUM)


_CRITICAL_PATHS = re.compile(
    r"(/boot|/etc/sudoers|/etc/shadow|/etc/passwd|/root|"
    r"/proc/sys/kernel|/dev/sd[a-z]|/dev/nvme|/sys/firmware)",
    re.IGNORECASE,
)

_USER_HOME = os.path.expanduser("~")


def _target_is_in_user_home(target: str) -> bool:
    if not target:
        return False
    try:
        # realpath resolves symlinks so a symlink-swap TOCTOU is caught here
        return os.path.realpath(target).startswith(_USER_HOME)
    except Exception:
        return False


def _target_is_critical(target: str) -> bool:
    if not target:
        return False
    try:
        resolved = os.path.realpath(target)
    except Exception:
        resolved = target
    return bool(_CRITICAL_PATHS.search(resolved))


def classify(intent: dict) -> ClassificationResult:
    """
    Classify an Intent Object into a risk tier.

    Args:
        intent: Validated Intent Object (must pass JSON schema validation first).

    Returns:
        ClassificationResult with tier, reason, reversibility.
    """
    action     = intent.get("action", "")
    target     = intent.get("target", "")
    risk_level = intent.get("risk_level", "")

    # Explicit critical override from intent
    if risk_level == "critical":
        return ClassificationResult(
            tier=Tier.HIGH,
            reason="Intent explicitly marked critical risk level",
            reversible=False,
        )

    # Critical target path: highest precedence after explicit "critical"
    if _target_is_critical(target):
        match = _CRITICAL_PATHS.search(os.path.realpath(target) if target else "")
        return ClassificationResult(
            tier=Tier.HIGH,
            reason=f"Target '{target}' is a protected system path",
            reversible=False,
            blocked_pattern=match.group(0) if match else None,
        )

    # Tier 3 destructive tools (e.g. fs.delete)
    if action in DESTRUCTIVE_TOOLS:
        return ClassificationResult(
            tier=Tier.HIGH,
            reason=f"{action} is a destructive operation — requires explicit approval",
            reversible=False,
        )

    # Tier 0 pure read-only tools
    if action in TIER0_TOOLS:
        return ClassificationResult(
            tier=Tier.READ_ONLY,
            reason=f"{action} is a read-only operation",
            reversible=True,
        )

    # Conditional-tier tools: today the only member is fs.write
    if action in CONDITIONAL_TIER_TOOLS:
        if action == "fs.write":
            if _target_is_in_user_home(target):
                return ClassificationResult(
                    tier=Tier.LOW,
                    reason="Write to user home directory — auto-execute with audit",
                    reversible=True,
                )
            return ClassificationResult(
                tier=Tier.HIGH,
                reason=f"fs.write to '{target}' is outside user home directory",
                reversible=False,
            )

    # Tier 2 system writes (package.install/remove/upgrade, service.start/stop/restart)
    if action in SYSTEM_WRITE_TOOLS:
        return ClassificationResult(
            tier=Tier.MEDIUM,
            reason=f"{action} modifies system-level configuration",
            reversible=action.startswith("package."),
        )

    # GUI read-only tools — Tier 0
    if action in GUI_READONLY_TOOLS:
        return ClassificationResult(
            tier=Tier.READ_ONLY,
            reason=f"{action} is a read-only GUI operation",
            reversible=True,
        )

    # GUI write tools — Tier 1 (user docs) or Tier 2 (system UI)
    if action in GUI_WRITE_TOOLS:
        if _target_is_in_user_home(target):
            return ClassificationResult(
                tier=Tier.LOW,
                reason=f"{action} targets user application — auto-execute with audit",
                reversible=True,
            )
        return ClassificationResult(
            tier=Tier.MEDIUM,
            reason=f"{action} is a GUI write operation on system UI",
            reversible=True,
        )

    # Unclassified action: defensive medium tier (audit + notify; do not auto-block,
    # because a missing tool name should be caught upstream by JSON-schema validation
    # of the Intent Object's `action` field. This fallback exists for resilience.)
    return ClassificationResult(
        tier=Tier.MEDIUM,
        reason=f"Unclassified action '{action}' — applying medium risk tier",
        reversible=True,
    )


# ── Pluggable classifier registry (M5.2b) ────────────────────────────────────

from typing import Callable

Classifier = Callable[[dict], ClassificationResult]

_REGISTRY: dict[str, Classifier] = {}


def register_classifier(name: str, fn: Classifier) -> None:
    _REGISTRY[name] = fn


def get_classifier(name: str) -> Classifier:
    if name not in _REGISTRY:
        raise KeyError(f"Unknown classifier strategy {name!r}. Available: {sorted(_REGISTRY)}")
    return _REGISTRY[name]


register_classifier("rules", classify)


# CLI for ad-hoc testing
if __name__ == "__main__":
    test_cases = [
        {"action": "system.status",   "target": "",                    "params": {}, "reason": "user_requested", "risk_level": "read_only"},
        {"action": "fs.read",         "target": "/etc/hosts",          "params": {}, "reason": "user_requested", "risk_level": "read_only"},
        {"action": "fs.write",        "target": f"{_USER_HOME}/notes", "params": {}, "reason": "user_requested", "risk_level": "low"},
        {"action": "fs.write",        "target": "/etc/nginx/nginx.conf","params": {}, "reason": "user_requested", "risk_level": "medium"},
        {"action": "fs.delete",       "target": "/var/log/app.log",    "params": {}, "reason": "user_requested", "risk_level": "high"},
        {"action": "service.restart", "target": "nginx",               "params": {}, "reason": "user_requested", "risk_level": "medium"},
        {"action": "package.install", "target": "curl",                "params": {}, "reason": "user_requested", "risk_level": "medium"},
        {"action": "fs.write",        "target": "/boot/grub/grub.cfg", "params": {}, "reason": "user_requested", "risk_level": "critical"},
    ]

    print(f"{'Action':<22} {'Target':<35} {'Tier':<14} {'HITL':<6} Reason")
    print("-" * 120)
    for intent in test_cases:
        result = classify(intent)
        print(
            f"{intent['action']:<22} "
            f"{intent['target']:<35} "
            f"Tier {int(result.tier)} {result.tier.name:<7} "
            f"{'YES' if result.requires_hitl else 'no':<6} "
            f"{result.reason}"
        )
