#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "========================================"
echo " Privileged Brain — Synthetic Data"
echo "========================================"

# Prefer the local (no API key) generator by default.
# Set USE_API=1 to use the Claude API generator instead.
USE_API=${USE_API:-0}

if [ "$USE_API" = "1" ]; then
  if [ -z "${ANTHROPIC_API_KEY:-}" ]; then
    echo "ERROR: USE_API=1 but ANTHROPIC_API_KEY is not set."
    echo "       Falling back to local generator."
    USE_API=0
  fi
fi

if [ "$USE_API" = "1" ]; then
  TARGET=${1:-5000}
  echo "Mode   : Claude API (teacher model)"
  echo "Target : $TARGET pairs"
  echo ""
  python3 scripts/generate_synthetic.py --target "$TARGET"
else
  echo "Mode   : Local (pre-generated by Claude, no API key needed)"
  echo ""
  python3 scripts/generate_synthetic_local.py
fi

echo ""
echo "Generating advanced complex pairs (pipes, jq, kubectl, docker, git, etc.)..."
python3 scripts/generate_synthetic_advanced.py

echo ""
echo "Re-processing datasets to include synthetic data..."
python3 scripts/process_datasets.py

echo ""
TRAIN_COUNT=$(wc -l < data/processed/train.jsonl)
VALID_COUNT=$(wc -l < data/processed/valid.jsonl)
echo "Updated dataset:"
echo "  train.jsonl : $TRAIN_COUNT examples"
echo "  valid.jsonl : $VALID_COUNT examples"
echo ""
echo "Next: bash 04_train.sh"
